name: Build Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Composer update
      run: composer update

    - name: Composer install
      run: composer install

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Use the version of Node.js required by your project

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn run build

    - name: Delete Node Modules
      run: rm -rf node_modules

    - name: Git config
      run: |
        git config --global user.email "jonas@vahajo.be"
        git config --global user.name "Github Actions"

    - name: Add changes
      run: git add .

    - name: Commit changes
      run: git commit -m "Build on $(date)"

    - name: Push to main
      run: git push -u origin main
